image:
  prefix: bruce1000/taskflow
  tag: v1.0.1
  pullPolicy: IfNotPresent

postgres:
  user: taskflow
  password: taskflow
  db: taskflow
  storageSize: 1Gi

otel:
  endpoint: http://otel-collector:4318

frontend:
  replicaCount: 1
  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "64Mi"
      cpu: "100m"

userService:
  replicaCount: 2
  hpa:
    enabled: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

taskService:
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPU: 70
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

notificationService:
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

apiGateway:
  replicaCount: 2
  hpa:
    enabled: false
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

redis:
  enabled: true
  fullnameOverride: redis
  architecture: standalone
  auth:
    enabled: false
  image:
    registry: docker.io
    tag: latest
  master:
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
