services:
  postgres:
    image: postgres:16-alpine
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    env_file:
      .env
    environment:
      OTEL_SERVICE_NAME: user-service
    depends_on:
      postgres:
        condition: service_healthy

  task-service:
    build: ./task-service
    env_file:
      .env
    environment:
      OTEL_SERVICE_NAME: task-service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    ports:
      - "3003:3003"
    env_file:
      .env
    environment:
      OTEL_SERVICE_NAME: notification-service
    depends_on:
      redis:
        condition: service_healthy

  api-gateway:
    build: ./api-gateway
    ports:
      - "3004:3004"
    env_file:
      .env
    environment:
      OTEL_SERVICE_NAME: api-gateway
    depends_on:
      - user-service
      - task-service
      - notification-service

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway

volumes:
  postgres_data:
