apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-cm
  namespace: staging
data:
  PORT: "3001"
  DATABASE_URL: postgresql://taskflow:taskflow@postgres:5432/taskflow
  OTEL_SERVICE_NAME: user-service
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318