kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true" 
    # Without this label, the NGINX Ingress pod stays Pending forever
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      # Port tunnels between your machine and the kind container
      # Without this, http://localhost does not respond even with Ingress deployed
  - role: worker
  - role: worker
