{
 "title": "Dashboards - 2",
 "time": { "from": "2026-04-03T13:56:32.010Z", "to": "2026-04-03T21:37:22.058Z" },
 "panels": [
  {
   "title": "Login Attempts ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(success) (rate(user_login_attempts_total[5m]))",
     "legendFormat": "{{success}}"
    }
   ]
  },
  {
   "title": "Tasks by Priority",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(priority) (tasks_by_priority_gauge)",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Transition rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(from_status, to_status) (rate(tasks_status_changes_total[5m])) * 60",
     "legendFormat": "{{from_status}} -> {{to_status}}"
    }
   ]
  },
  {
   "title": "Task created per minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(tasks_created_total[1m])) * 60",
     "legendFormat": "task/min"
    }
   ]
  }
 ]
}