apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-cm
  namespace: staging
data:
  PORT: "3002"
  REDIS_URL: redis://redis:6379
  DATABASE_URL: postgresql://taskflow:taskflow@postgres:5432/taskflow
  OTEL_SERVICE_NAME: task-service
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318