apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: task-service
          image: bruce1000/taskflow-task-service:v1.0.1
          envFrom:
            - configMapRef:
                name: task-service-cm
          ports:
            - containerPort: 3002
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"