apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-cm
  namespace: staging
data:
  PORT: "3004"
  USER_SERVICE_URL: http://user-service:3001
  TASK_SERVICE_URL: http://task-service:3002
  NOTIFICATION_SERVICE_URL: http://notification-service:3003
  OTEL_SERVICE_NAME: api-gateway
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318