apiVersion: v1
kind: Secret
metadata:
  name: taskflow-alertmanager-config
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      smtp_smarthost: {{ .Values.alertmanagerConfig.smtp.host | quote }}
      smtp_from: {{ .Values.alertmanagerConfig.smtp.from | quote }}
      smtp_auth_username: {{ .Values.alertmanagerConfig.smtp.username | quote }}
      smtp_auth_password: {{ .Values.alertmanagerConfig.smtp.password | quote }}
    receivers:
      - name: email
        email_configs:
          - to: {{ .Values.alertmanagerConfig.smtp.to | quote }}
            send_resolved: true
      - name: "null"
    route:
      receiver: "null"
      routes:
        - matchers:
            - alertname = "HighP95Latency"
          receiver: email
          group_wait: 5s
          group_interval: 30s
          repeat_interval: 1h
