apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: notification-service
          image: bruce1000/taskflow-notification-service:v1.0.1
          envFrom:
            - configMapRef:
                name: notification-service-cm
          ports:
            - containerPort: 3003
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"